server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5000ms
      database: 0
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 20
          min-idle: 10
          time-between-eviction-runs: 60s
jwt:
  secret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
  expires-in: 120

logging:
  level:
    top.kunjz.filterinterceptor.filter.RateLimitFilter: DEBUG