server:
  port: 8888

team:
  name: "Web2班"
  leader: zjk
  phone: "18136256911"
  age: ${random.int(1,4)}

aliyun-oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com"   # 地域域名
  bucket: "zjk629"
  accessKey: "xxxxxxxxxxxxxxxxxxxxxxxxxx"
  secretKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxV"
  dir: "img/"


custom:
  qrcode:
   content: "https://www.baidu.com"
spring:
 mail:
  host: smtp.qq.com #发送邮件服务器
  username: 3348805775@qq.com #你的qq邮箱
  password: cniwdsndijqvchdd #客户端授权码
  protocol: smtp #发送邮件协议
  properties.mail.smtp.auth: true
  properties.mail.smtp.port: 465 #端口号465或587
  properties.mail.display.sendmail: Spring Boot #可以任意
  properties.mail.display.sendname: Spring Boot Guide Email #可以任意
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true
  properties.mail.smtp.ssl.enable: true
  default-encoding: utf-8