server:
  port: 8888

team:
  leader: "Web2班"
  phone: "18136256911"
  age: 5
  createDate: "2020-01-01"

aliyun-oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com"   # 地域域名
  bucket: "zjk629"
  accessKey: ${ALI_KEY_ID}
  secretKey: ${ALI_KEY_SECRET}
  dir: "img/"


custom:
  qrcode:
   content: "https://www.baidu.com"

spring:
 mail:
  host: smtp.qq.com
  username: 3348805775@qq.com
  password: cniwdsndijqvchdd
  protocol: smtp
  properties.mail.smtp.auth: true
  properties.mail.smtp.port: 465
  properties.mail.display.sendmail: Spring Boot
  properties.mail.display.sendname: Spring Boot Guide Email
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true
  properties.mail.smtp.ssl.enable: true
  default-encoding: utf-8